import template from '../template'

const sys = 'infraSubSys'

export default [
  // template(sys, 'dataSource', {}),
  template(sys, 'dataSourceType', {}),
  // template(sys, 'deliverable', {}),
  template(sys, 'deliverableType', {}),
  // template(sys, 'emplPosition', {}),
  // template(sys, 'emplPositionFulfillment', {}),
  // template(sys, 'emplPositionReportingStruct', {}),
  // template(sys, 'emplPositionResponsibility', {}),
  template(sys, 'emplPositionType', {}),
  // template(sys, 'employment', {}),
  // template(sys, 'enumeration', {}),
  template(sys, 'enumerationType', {}),
  // template(sys, 'geo', {}),
  // template(sys, 'geoAssoc', {}),
  template(sys, 'geoAssocType', {}),
  template(sys, 'geoType', {}),
  template(sys, 'mimeType', {}),
  template(sys, 'periodType', {}),
  template(sys, 'priorityType', {}),
  // template(sys, 'quantityBreak', {}),
  template(sys, 'quantityBreakType', {}),
  // template(sys, 'rateAmount', {}),
  template(sys, 'rateType', {}),
  template(sys, 'ratingType', {}),
  template(sys, 'requirementType', {}),
  template(sys, 'responsibilityType', {}),
  template(sys, 'saleType', {}),
  template(sys, 'salesLeadAssocType', {}),
  template(sys, 'salesLeadType', {}),
  template(sys, 'skillType', {}),
  // template(sys, 'statusItem', {}),
  template(sys, 'statusType', {}),
  // template(sys, 'statusValidChange', {}),
  template(sys, 'uom', {}),
  template(sys, 'uomType', {}),
  // template(sys, 'validResponsibility', {}),
]